sudo: false
language: ruby
rvm:
  - 2.4.2
before_install:
  - gem install bundler -v 1.16.0
install:
  - npm install -g ganache-cli
  - bundle install
before_script:
  - ganache-cli -p 4285 &

notifications:
  email: false
